### ISSUE TITLE
点击build.bat后，生成的bin文件夹下只有一个空文件夹Debug

### ISSUE THREAD

**Issue by xiaomx32** [mayerui/sudoku#20]

**Comment by Cstardust** [comment]
我也是这个问题 请问你解决了嘛

**Comment by xiaomx32** [comment]
> 我也是这个问题 请问你解决了嘛

没有呢，再等等作者吧

**Comment by marblemm** [comment]
> > 我也是这个问题 请问你解决了嘛
> 
> 没有呢，再等等作者吧

这个问题是因为源码中input.cpp的编码是utf-8无bom头的，将此文件改成带bom头，就可以编译过了
编译错误提示：error C2001:常量中有换行符
解决链接：https://www.cnblogs.com/kuliuheng/p/3397796.html

**Comment by Cstardust** [comment]
> > > 我也是这个问题 请问你解决了嘛
> > 
> > 
> > 没有呢，再等等作者吧
> 
> 这个问题是因为源码中input.cpp的编码是utf-8无bom头的，将此文件改成带bom头，就可以编译过了
> 编译错误提示：error C2001:常量中有换行符
> 解决链接：https://www.cnblogs.com/kuliuheng/p/3397796.html

谢谢作者帮助，确实是那个原因，我解决了。不知道那位xd解决没有。

**Comment by xiaomx32** [comment]
> > > > 我也是这个问题 请问你解决了嘛
> > > 
> > > 
> > > 没有呢，再等等作者吧
> > 
> > 
> > 这个问题是因为源码中input.cpp的编码是utf-8无bom头的，将此文件改成带bom头，就可以编译过了
> > 编译错误提示：error C2001:常量中有换行符
> > 解决链接：https://www.cnblogs.com/kuliuheng/p/3397796.html
> 
> 谢谢作者帮助，确实是那个原因，我解决了。不知道那位xd解决没有。

是直接在input.cpp文件里加上“0xEF 0xBB 0xBF”吗？我试过了，这样也不行。

**Comment by VoidmatrixHeathcliff** [comment]
Win下可能需要使用拥有开发环境的DeveloperCommandPrompt运行`build.bat`，或者使用控制台运行`build.bat`查看输出的问题

**Comment by Cstardust** [comment]
> > > > > 我也是这个问题 请问你解决了嘛
> > > > 
> > > > 
> > > > 没有呢，再等等作者吧
> > > 
> > > 
> > > 这个问题是因为源码中input.cpp的编码是utf-8无bom头的，将此文件改成带bom头，就可以编译过了
> > > 编译错误提示：error C2001:常量中有换行符
> > > 解决链接：https://www.cnblogs.com/kuliuheng/p/3397796.html
> > 
> > 
> > 谢谢作者帮助，确实是那个原因，我解决了。不知道那位xd解决没有。
> 
> 是直接在input.cpp文件里加上“0xEF 0xBB 0xBF”吗？我试过了，这样也不行。

我是用Nodepad++改成带bom头的。不过建议还是直接用ubuntu吧。。如果用windows后面还会有莫名其妙的bug。。。

**Comment by mzhongyy** [comment]
我也遇到了，“编译错误提示：error C2001:常量中有换行符”  确实如上面所说应该是windows中文编码的问题，这里的话把出错行的最后的中文感叹号去掉就能成功编译，但运行时依旧会中文乱码，建议把项目所有的中文改为英文，就能正确运行
