### ISSUE TITLE
C++ ANSI控制码无法改变字体颜色

### ISSUE THREAD

**Issue by ZhDuoYu** [mayerui/sudoku#22]
windows下VS2017
代码：
int main()
{
	cout << "\033[" << 34 << "m"<<" test....";
	system("pause");
	return 0;
}
输出：
[34m test....请按任意键继续. . .

应该输出蓝色字体的 test.... 才对

**Comment by ContentedCatEars** [comment]
在另一台电脑上Windows-VS2019下输出的是正确的蓝色字体，我自己的电脑上不行。请问应该如何进行设置呢？
