### ISSUE TITLE
在windows平台导入vs产生的两个问题及解决方法

### ISSUE THREAD

**Issue by mzhongyy** [mayerui/sudoku#28]
1. 程序由于中文符号不能正确编译，报“编译错误提示：error C2001:常量中有换行符”，其实是由于input.cpp中的中文“！”造成的，删除！即可编译成功，但执行后命令行依旧会有中文乱码问题，因此建议直接将所有中文输出修改为英文；

2. 不能断点调试，提示断点被跳过不能进行调试，不能调试的原因是cmake中有地方写的没兼容msvc.去掉CmakeLists.txt中的
`SET(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb ")#就是这两行东东`
`SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")`
去掉这两行就好了

**Comment by mayerui** [comment]
谢谢帮忙发现问题以及提出解决方案。
由于我目前主要使用的开发平台为Linux，所以对其他平台的兼容性方面关注较少。如果已经找到解决方案的话，欢迎提出PR来修复或优化，多谢。
