### ISSUE TITLE
怎么改变输入数字的颜色呢？

### ISSUE THREAD

**Issue by wyjchain** [mayerui/sudoku#32]
怎么改变输入数字的颜色呢？

**Comment by mayerui** [comment]
暂时没有支持改颜色的功能，可以详细说一下需求吗？

**Comment by wyjchain** [comment]
那那个color.h有什么作用呢？

**Comment by mayerui** [comment]
> 我的idea是能让数字显示的更清楚一点，还有那个游标太小了可以调大一点吗？还有就是能不能多四条比较明显的线（就是一个井字线或者深一点）好容易看跑偏

1. 游标目前使用的是“^”符号，在目前纯ascii的显示下，我没想到更好的符号来代替，你可以帮忙想想。
2. 现在Linux下，大九宫格之间的分隔已经比较明显了，你能附上在你环境中运行的截图吗？
![image](https://user-images.githubusercontent.com/25812837/232263974-6f13a28b-e75c-44b5-bbd6-95d406fb7ce9.png)

**Comment by mayerui** [comment]
> 那那个color.h有什么作用呢？

这个文件确实提供了C++流输出的颜色控制功能。但现在版本代码中数字的颜色是写死的，你的需求是通过配置文件的方式，由用户来修改颜色吗？

**Comment by mayerui** [comment]
https://github.com/mayerui/sudoku/pull/43
这个pr优化了九宫格分区显示效果
