### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lh13329089918** [mayerui/sudoku#41]
windows 环境下这个报错该如何解决？
![图片](https://github.com/user-attachments/assets/8b786c6a-0058-4395-8ceb-3eeff5ec0359)

**Comment by mayerui** [comment]
是否有安装编译器

**Comment by lh13329089918** [comment]
安装了呀，MinGW64

**Comment by mayerui** [comment]
检查环境变量有没有配置mingw64的路径，以及在你的终端中gcc -v有没有输出。
看你截图的报错就是CMake找不到编译器。

**Comment by lh13329089918** [comment]
这个 真的配置了，路径重新都设置了。
![图片](https://github.com/user-attachments/assets/7db9e5ca-d2e5-4ba5-a1ab-bbf56743fd5d)

**Comment by mayerui** [comment]
我猜测是在Windows平台，CMake默认会用VS的nmake作为构建系统。
你可以尝试使用cmake ..  -G "MinGW Makefiles"替代build.bat中第3行的cmake ..命令，来指定使用MinGW进行构建。我本地测试通过。
![image](https://github.com/user-attachments/assets/79c28dcf-094a-4d65-96ad-159bed963892)
