### ISSUE TITLE
关于CScence::init()的xy_block成员填充过于复杂

### ISSUE THREAD

**Issue by Peas-Li** [mayerui/sudoku#44]
void CScene::init()
{
    memset(_map, UNSELECTEN, sizeof(_map));

    int col = 0;
    int row = 0;

    for(col = 0; col < _max_column; ++col)
    {
        CBlock column_block;

        for(row = 0; row < _max_column; ++row)
        {
            column_block.push_back(_map + row * _max_column + col);
        }

        _column_block[col] = colunm_block;
    }

    for(row = 0; row < _max_column; ++row)
    {
        CBlock row_block;

        for(col = 0; col < _max_column; ++col)
        {
            row_block.push_back(_map + row * _max_column + col);
        }

        _row_block[row] = row_block;
    }

    for(row = 0; row < _max_column; ++row)
    {
        for(col = 0; col < _max_column; ++col)
        {
            _xy_block[row / 3][col / 3].push_back(_map + row * _max_column + col);
        }
    }

    return;
}

**Comment by mayerui** [comment]
欢迎提pr
