### ISSUE TITLE
sudoku结构过于固定问题

### ISSUE THREAD

**Issue by Stranger-Jie** [mayerui/sudoku#49]
![image](https://github.com/user-attachments/assets/f759a016-2a82-44af-b7e1-9419724202ce)
在此基础上能够增加生成数独的多样性，如果可以我可以尝试添加一个回溯法来生成解

**Comment by Stranger-Jie** [comment]
![image](https://github.com/user-attachments/assets/f56672b4-74e8-4b99-b56d-53c3c87dbfd6)
一个简单的实现

**Comment by Stranger-Jie** [comment]
![image](https://github.com/user-attachments/assets/5d418352-8d09-44c3-a608-2b3411855bed)

**Comment by Stranger-Jie** [comment]
@mayerui 我尝试加入了生成数独的多样性，游玩下来休闲很不错，简单明了，给新手是个很不错的项目，我会推荐给其他人的（特别是新手！！）

**Comment by mayerui** [comment]
谢谢你的pr，已合并。老的generate方法能产生的布局是A99个，应该够玩，但你的时间理论上确实更多。

**Comment by Stranger-Jie** [comment]
1. 固定结构很容易被发现出特定的规律，比如同一宫格内，每行三个数是固定的，求解起来会很简单。
2. 对于挖空生成题目时，还需要考虑一下，如果随机挖空的话，可能生成的不是唯一解数独。
谢谢你的回复！
