### ISSUE TITLE
scene文件中未包含#include<string>头文件导致运行出错

### ISSUE THREAD

**Issue by James-yang-china** [mayerui/sudoku#5]

**Comment by mayerui** [comment]
没有复现你说的问题。
能不能描述更详细一些？是编译错误还是运行错误？截图有吗

**Comment by James-yang-china** [comment]
vs2017直接运行会有以下错误，在scene.cpp中加入#include<string&gt;头文件后可以正常运行
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mohuang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上6:09
收件人:&nbsp;"mayerui/sudoku"<sudoku@noreply.github.com&gt;;
抄送:&nbsp;"心如止水"<1053902196@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mayerui/sudoku] scene文件中未包含#include<string&gt;头文件导致运行出错 (#5)




没有复现你说的问题。
 能不能描述更详细一些？是编译错误还是运行错误？截图有吗

**Comment by mayerui** [comment]
你好，该项目暂时不提供visual studio的工程文件，所以你说的VS2017直接运行是自己建了个工程把源代码添加进去吗？
该项目推荐的构建方法是安装cmake工具后使用build.bat一键编译。
我的开发环境只安装了VS2019版本，编译是ok的。你也可以尝试使用VS2017内置的cmake插件（不清楚是否有内置，2019是有的）来构建。
